require:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
  TargetRubyVersion: 3.0

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/EmptyClass:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  EnforcedStyle: brackets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "()"
    "%I": "()"
    "%r": "()"
    "%w": "()"
    "%W": "()"

Style/WordArray:
  EnforcedStyle: brackets
